=== txd220/td_domain_context/Territory/territory_api_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/product.schema.json",
    "title": "Territory",
    "description": "A grouping of customers within a given geography managed by a Sherwin Sales Representative",
    "type": "object",
    "properties": {
        "territoryId": {
            "description":"Business key for territory.  Two-part natural key with businessUnit.",
            "type": "string"
        },
        "businessUnit": {
            "description":"Sherwin business unit the territory belongs too.  Two-part natural key with territoryId.",
            "type":"string"
        },
        "name": {
            "description":"Sherwin business name given for the territory",
            "type":"string"
        },
        "source": {
            "description":"Source system the territory came from",
            "type":"string"
        },
        "role": {
            "description":"Heirarchical role territory belongs to",
            "type":"string"
        },
        "heirarchyCode": {
            "description":"The code for the heirarchy associated with this territory",
            "type":"string"
        },
        "location": {
            "description":"Geographic region for the territory.  UNITES STATES, US, etc.",
            "type": "object",
            "properties": {
                "code": {
                    "description":"Unique identifier for a specific territory.  TODO: Feels like an ENUM",
                    "type":"string",
                    "minLength": 2,
                    "maxLength": 7
                },
                "name": {
                    "description": "Human readable unique identifier for the location",
                    "type": "string"
                }
            },
            "required": ["code", "name"]
        },
        "owners": {
            "description": "A collection of relationships to other territories.",
            "type": "array",
            "items" : {
                "type": "object",
                "properties": {
                    "type": {
                        "description": "Classification for the ownership.  TODO: Feels like an ENUM",
                        "type": "string"
                    },
                    "code": {
                        "description": "Unique identifier for the ownership record",
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 7
                    },
                    "lastUpdatedDate": {
                        "description": "Date of the last change to the ownership record",
                        "type": "string"
                    }
                },
                "required": ["type", "code"]
            }
        },
        "workforce": {
            "description": "A collection of Sherwin workers that have a relationship with the territory.",
            "type": "array",
            "items" : {
                "type": "object",
                "properties": {
                    "personNumber": {
                        "description": "Unique identifier for the worker",
                        "type": "string"
                    },
                    "adUserId": {
                        "description": "Active Directory user ID",
                        "type": "string"
                    },
                    "firstName": {
                        "description": "Worker's legal first name",
                        "type": "string"
                    },
                    "lastName": {
                        "description": "Worker's legal last name",
                        "type": "string"
                    },
                    "fullName": {
                        "description": "Worker's full name",
                        "type": "string"
                    },
                    "effectiveStartDate": {
                        "description": "Date the worker.s relationship with the territory began",
                        "type": "string"
                    },
                    "effectiveEndDate": {
                        "description": "Date the worker's relationship with the territory ends",
                        "type": "string"
                    }
                },
                "required": ["personNumber", "firstName", "lastName"]
            }
        },
        "lastUpdatedDate": {
            "description":"The date the terriroty was last modified in the source system",
            "type":"string"
        }
    },
    "required": ["territoryId", "name", "businessUnit", "role","heirarchyCode"]
}

=== txd220/td_domain_context/Territory/territory_api_sample.json
{
    "territoryId": "ABCDEFGHIJKLMN",
    "name": "ABCDEFGHIJK",
    "businessUnit": "ABCD",
    "role": "ABCDEFGHIJKLMNOPQRSTUVW",
    "heirarchyCode": "ABCDEFGHI",
    "source": "ABCDEFGHIJKLM",
    "location": {
      "code": "ABCDEF",
      "name": "ABCDEFGHIJK"
    },
    "owners": [
      {
        "type": "ABCDEFGHIJKLMNOPQRSTUVWX",
        "code": "ABCDE",
        "lastUpdatedDate": "ABCDEFGHIJKLM"
      },
      {
        "type": "ABCDEFGHIJKLMNOPQRSTUVWXYZA",
        "code": "ABCD",
        "lastUpdatedDate": "ABCDEFGHIJKLMNOPQRSTUVWXY"
      }
    ],
    "workforce": [
      {
        "personNumber": "ABCDE",
        "firstName": "ABCDEFGHIJKLMNOPQRSTUVWXYZABC",
        "lastName": "ABCDEFGHIJKLMN",
        "adUserId": "ABCDEFGHIJKLMNOPQ",
        "fullName": "ABCDEFG",
        "effectiveStartDate": "ABCDEFGHI",
        "effectiveEndDate": "ABCDEFG"
      },
      {
        "personNumber": "ABCDEFGHIJKLMNOPQRSTUVW",
        "firstName": "ABCDEFGHIJKLMNOPQ",
        "lastName": "ABCDEFGHIJKLMNOPQ",
        "adUserId": "ABCDE",
        "fullName": "ABCDEFGHIJKLMNOPQRS",
        "effectiveStartDate": "ABCDEFGHI",
        "effectiveEndDate": "ABCDEF"
      }
    ],
    "lastUpdatedDate": "ABCDEFGHIJKLM"
  }
